yarnPath: .yarn/releases/yarn-3.2.3.cjs

# https://github.com/chalk/chalk/issues/531#issuecomment-1146705502
packageExtensions:
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": npm:ansi-styles@6.1.0
      "#supports-color": npm:supports-color@9.2.2

  "@astrojs/markdown-remark@*":
    dependencies:
      "hast-util-to-html": "*"
